#!/usr/bin/env bash
(cd glibc && git pull origin release/2.43/master)
mkdir glibc-build
cd glibc-build

../glibc/configure \
    --host=riscv64-linux-gnu \
    --prefix=/usr \
    --with-headers=/output/headers/include \
    --disable-werror

make
mkdir /glibc-install
make install DESTDIR=/glibc-install
(cd /glibc-install && tar zcvfp /output/glibc.tar.gz *)

