#!/bin/bash
mkdir -p _install/{bin,sbin,etc,proc,sys,usr/bin,usr/sbin,dev,lib}
(cd _install && tar zxvf /output/busybox.tar.gz)
cat <<'EOF' > _install/init
#!/static/bin/sh
export PATH=/static/sbin:/static/bin:/static/usr/sbin:/static/usr/bin

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev

echo "Welcome to RISC-V Linux!"
mkdir -p /mnt/host
mount -t 9p -o trans=virtio,version=9p2000.L hostshare /mnt/host || true

if [[ -d /lib/modules/arch ]]
then
    mkdir /lib/modules/`uname -r`
    mv /lib/modules/* /lib/modules/`uname -r`/
fi

exec setsid cttyhack sh
EOF
chmod +x _install/init
(cd _install && find . -print0 | cpio --null -ov --format=newc | gzip -9 > /output/initramfs.cpio.gz)
