#!/bin/bash
mkdir -p _install/{bin,sbin,etc,proc,sys,usr/bin,usr/sbin,dev,lib}
mkdir -p _install/static/{bin,sbin,usr/bin,usr/sbin}
cd _install
cp /output/busybox static/bin/
cat /output/busybox-links | while read l
do
    ln -s /static/bin/busybox static/$l
done
cat <<'EOF' > init
#!/static/bin/sh
export PATH=/static/sbin:/static/bin:/static/usr/sbin:/static/usr/bin

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev

echo "Welcome to RISC-V Linux!"
mkdir -p /mnt/host
mount -t 9p -o trans=virtio,version=9p2000.L hostshare /mnt/host || true

if [[ -d /lib/modules/arch ]]
then
    mkdir /lib/modules/`uname -r`
    mv /lib/modules/* /lib/modules/`uname -r`/
fi

exec setsid cttyhack sh
EOF
chmod +x init
find . -print0 | cpio --null -ov --format=newc | gzip -9 > /output/initramfs.cpio.gz
