#!/bin/bash
cd linux

make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- defconfig
./scripts/config --enable CONFIG_NET_9P
./scripts/config --enable CONFIG_NET_9P_VIRTIO
./scripts/config --enable CONFIG_9P_FS
./scripts/config --enable CONFIG_9P_FS_POSIX_ACL
./scripts/config --enable CONFIG_VIRTIO_PCI
time make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- -j$(nproc)
cp -p arch/riscv/boot/Image* /output/

mkdir /modules
find . -name '*.ko' | while read mod
do
    mkdir -p /modules/$(dirname $mod)
    cp $mod /modules/$mod
done
(cd /modules && tar zcvfp /output/linux-modules.tar.gz *)

mkdir /headers
make headers_install INSTALL_HDR_PATH="/headers"
(cd /headers && tar zcvfp /output/linux-headers.tar.gz *)
