FROM ubuntu:24.04
# FROM --platform=linux/arm64 ubuntu:24.04

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# 1. Install build essentials and the RISC-V cross-toolchain
RUN apt-get update && apt-get install -y \
    build-essential \
    sbcl \
    gcc-riscv64-linux-gnu \
    binutils-riscv64-linux-gnu \
    git \
    time \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Clone SBCL source
RUN git clone https://github.com/sbcl/sbcl.git .

# Set environment variables for the cross-compiler
ENV SBCL_ARCH=riscv64

COPY build-sbcl-internal .
