#!/static/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/static/sbin:/static/bin:/static/usr/sbin:/static/usr/bin

mkdir -p dev proc sys
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev

ROOT=$(sed -n 's/.*root=\([^ ]*\).*/\1/p' /proc/cmdline)
echo "Trying to mount root from $ROOT_DEV"

case "$ROOT" in
    UUID=*)  ROOT="/dev/disk/by-uuid/${ROOT#UUID=}" ;;
    LABEL=*) ROOT="/dev/disk/by-label/${ROOT#LABEL=}" ;;
esac

echo "Waiting for root device $ROOT..."
TIMER=0
while [ ! -b "$ROOT" ] && [ $TIMER -lt 10 ]; do
    sleep 1
    TIMER=$((TIMER + 1))
done

if [ -b "$ROOT" ]; then
    echo "Mounting $ROOT..."
    mkdir -p /newroot
    mount -o ro "$ROOT" /newroot  # Mount as read-only initially
    mount -t proc none /newroot/proc
    mount -t sysfs none /newroot/sys
    mount -t devtmpfs devtmpfs /newroot/dev
    echo 0 > /proc/sys/debug/exception-trace

    echo "Switching to real root..."
    exec /static/sbin/switch_root /newroot /init
else
    echo "ERROR: Root device $ROOT not found!"
    echo "Dropping to recovery shell..."
    echo
    echo "Welcome to RISC-V Linux!"
    mkdir -p /mnt/host
    exec /static/usr/bin/setsid cttyhack sh
fi
