#!/usr/bin/env bash

qemu-system-riscv64 -m 2G -nographic -machine virt \
    -bios default \
    -kernel output/u-boot.bin \
    -drive file=root.qcow2,format=qcow2,id=sda,if=none \
    -device virtio-blk-device,drive=sda
