#!/usr/bin/env bash

if [[ $1 = "--share" ]]
then
    share="-virtfs local,path=$2,mount_tag=hostshare,security_model=none,id=hostshare"
fi

qemu-system-riscv64 -nographic -machine virt \
    -kernel output/Image \
    -append "console=ttyS0" \
    -initrd output/initramfs.cpio.gz $share
